apiVersion: 1
datasources:
- name: My datasource
  type: elasticsearch
  access: proxy
  orgId: 1
  url: http://192.168.0.108:9200
  user: 
  database: 
  allowUiUpdates: true
  isDefault: true
  # jsonData:
  #   sslmode: 'disable'
  #   postgresVersion: 1200
  #   timescaledb: false
  secureJsonData:
    password: ""
  version: 1
  editable: true